KS-3-3 initialize 1 var, add console output
ddm59/KotlinSprint pull request #12
Opened 2024-11-28 12:08 UTC by ddm59

initialize 1 var, add console output

2024-11-28 16:34 UTC, ievetrovdev requested changes
По поводу неймингов веток отписал ранее

2024-11-28 16:34 UTC, ievetrovdev commented on src/main/kotlin/lesson3_3/lesson3_task3.kt
> +    var  number = 9
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-11-29 02:32 UTC, ddm59 commented on src/main/kotlin/lesson3_3/lesson3_task3.kt
> +    var  number = 9
Стараюсь. Иногда местами вылетает из головы.

2024-11-30 10:10 UTC, ievetrovdev approved these changes

2024-11-30 11:26 UTC, merged