KS-4-2- released weight and volume check for average
ddm59/KotlinSprint pull request #16
Opened 2024-11-29 06:08 UTC by ddm59

released weight and volume check for average

2024-11-29 22:41 UTC, ievetrovdev requested changes

2024-11-29 22:41 UTC, ievetrovdev commented on src/main/kotlin/lesson4_2/lesson4_task2.kt
> +
Давай не будем оставлять более одной пустой строки подряд, что бы не усложнять чтение кода

2024-11-30 11:49 UTC, ddm59 commented on src/main/kotlin/lesson4_2/lesson4_task2.kt
> +
Ок. так же вынесу логику в переменную, по замечанию к задаче 4-1

2024-11-30 20:35 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-12-01 11:31 UTC, merged