KS-4-3- created cultivation monitoring check system
ddm59/KotlinSprint pull request #17
Opened 2024-11-29 07:01 UTC by ddm59

created cultivation monitoring check system

2024-11-30 20:36 UTC, ievetrovdev requested changes

2024-11-30 20:36 UTC, ievetrovdev commented on src/main/kotlin/lesson4_3/lesson4_task3.kt
> +    var conditionCheck = weatherCheck && tentCheck && (currentHumidity == REQUIRED_HUMIDITY) && (currentSeason != BAD_SEASON)
Все верно, но для weatherCheck  и tentCheck  тоже нужна константа для сравнения

2024-12-01 10:29 UTC, ddm59 commented on src/main/kotlin/lesson4_3/lesson4_task3.kt
> +    var conditionCheck = weatherCheck && tentCheck && (currentHumidity == REQUIRED_HUMIDITY) && (currentSeason != BAD_SEASON)
Исходные значения выделил в константы. Входящие значения которые по идее должны вводится не стал обьявлять как val ,  так как по идее они могут меняться. условия проверки разделил на несколько переменных для удобства чтения.

2024-12-01 22:34 UTC, ievetrovdev approved these changes
Все верно, можно было обойтись и без weatherCheck и tentCheck

2024-12-02 03:21 UTC, merged