KS-8-1 views count from array
ddm59/KotlinSprint pull request #37
Opened 2024-12-05 08:13 UTC by ddm59

views count from array

2024-12-05 19:00 UTC, ievetrovdev requested changes

2024-12-05 19:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task1.kt
> +        advertisingViews[0] = (50..1000).random()  // Генерация массива с просмотрами
Комментированный код лучше не оставлять, если на это нет действительно веских причин. Предлагаю почистить.

2024-12-05 19:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task1.kt
> +        weekViews += i                                  //Подсчет кол-ва просмотров за неделю
Можно использовать экстеншн функцию `sum()` для массива

2024-12-05 19:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task1.kt
> +        advertisingViews[0] = (50..1000).random()  // Генерация массива с просмотрами
А здесь ты не используешь счетчик для заполнения массива)

2024-12-06 04:10 UTC, ddm59 commented on src/main/kotlin/lesson_8/lesson8_task1.kt
> +        advertisingViews[0] = (50..1000).random()  // Генерация массива с просмотрами
Точно. Проглядел не тот код вставил.

2024-12-06 18:19 UTC, ievetrovdev approved these changes

2024-12-06 18:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task1.kt
> +    for (i in 0..6 ){
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-12-07 12:18 UTC, merged