KS-1-5 Initialized variable.formatted output
ddm59/KotlinSprint pull request #4
Opened 2024-11-14 06:28 UTC by ddm59

Initialized variable.
calculated values
formatted output

2024-11-14 13:25 UTC, ievetrovdev requested changes

2024-11-14 13:25 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +            "%02d:%02d:%02d", secondsInSpace / 3600, (secondsInSpace % 3600) / 60, secondsInSpace % 60
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это магические числа, что тоже не является хорошей практикой.
Для чтения удобства советую не пренебригать переменными

2024-11-14 13:37 UTC, ddm59 commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +            "%02d:%02d:%02d", secondsInSpace / 3600, (secondsInSpace % 3600) / 60, secondsInSpace % 60
> Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это магические числа, что тоже не является хорошей практикой. Для чтения удобства советую не пренебригать переменными

Ок. я подумывал об этом. Но почему то откинул эту идею) спасибо .

2024-11-14 14:52 UTC, ddm59 reviewed
Просьба проверить

2024-11-15 07:19 UTC, ievetrovdev requested changes

2024-11-15 07:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val secondsInSpace: Int = timeInSpaceInSeconds % 60
Голые числа это в том числе 60 и 3600, эти значения всегда неизменны, потому их стоит вывести в константы. 6480 же потенциально может изменится, поэтому просто переменная 
Нейминг констант отличен от обычных переменных. В документации по ссылке есть более полное описание стайл гайда

2024-11-28 07:20 UTC, ievetrovdev approved these changes

2024-11-28 07:42 UTC, merged