KS-2-1 calculated arithmetic mean
ddm59/KotlinSprint pull request #5
Opened 2024-11-14 07:04 UTC by ddm59

calculated arithmetic mean

2024-11-14 13:27 UTC, ievetrovdev requested changes

2024-11-14 13:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task1.kt
> +    println((3.0+4.0+3.0+5.0)/4)
Такой хоть и рабочий, но не изменяем и масштабируем. Да и сторонний читатель ничего не поймет. Давай добавим переменные под начальные данные 
И не забывай про форматирование

2024-11-14 15:10 UTC, ddm59 reviewed
прошу проверить

2024-11-28 07:21 UTC, ievetrovdev approved these changes

2024-11-28 07:43 UTC, merged