KS-11-2 User2 Class
ddm59/KotlinSprint pull request #53
Opened 2024-12-10 14:41 UTC by ddm59

User2 Class

2024-12-10 20:35 UTC, ievetrovdev requested changes
В аннотации к уроку я упоминаю создавать классы в одном файле. Перемести плиз)

2024-12-10 20:35 UTC, ievetrovdev commented on src/main/kotlin/lesson11_2/User2.kt
> +    var bio: String,
Обрати внимание в ТЗ био - необязательное для заполнения свойство. Как сделать так, чтобы не нужно было его заполнять при создании объекта?

2024-12-10 20:35 UTC, ievetrovdev commented on src/main/kotlin/lesson11_2/User2.kt
> +    var email: String,
Изменяемые переменные не нужны, большинство данных инициализируется один раз при создании объекта

2024-12-11 06:44 UTC, ddm59 commented on src/main/kotlin/lesson11_2/User2.kt
> +    var email: String,
оставил изменяемыми только password и bio так как они меняются . Так же перенес все в один файл

2024-12-11 19:57 UTC, ievetrovdev approved these changes

2024-12-12 13:20 UTC, merged